export const POST_REGISTRATION_START = "POST_REGISTRATION_START";
export const POST_REGISTRATION_SUCCESS = "POST_REGISTRATION_SUCCESS";
export const POST_REGISTRATION_FAILURE = "POST_REGISTRATION_FAILURE";

export const POST_LOGIN_START = "POST_LOGIN_START";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE = "POST_LOGIN_FAILURE";

export const GET_USERCREATEDPICKUPS_START = "GET_USERCREATEDPICKUPS_START";
export const GET_USERCREATEDPICKUPS_SUCCESS = "GET_USERCREATEDPICKUPS_SUCCESS";
export const GET_USERCREATEDPICKUPS_FAILURE = "GET_USERCREATEDPICKUPS_FAILURE";

export const POST_ADDNEWPICKUP_START = "POST_ADDNEWPICKUP_START";
export const POST_ADDNEWPICKUP_SUCCESS = "POST_ADDNEWPICKUP_SUCCESS";
export const POST_ADDNEWPICKUP_FAILURE = "POST_ADDNEWPICKUP_FAILURE";

export const DELETE_USERCREATEDPICKUP_START = "DELETE_USERCREATEDPICKUP_START";
export const DELETE_USERCREATEDPICKUP_SUCCESS = "DELETE_USERCREATEDPICKUP_SUCCESS";
export const DELETE_USERCREATEDPICKUP_FAILURE = "DELETE_USERCREATEDPICKUP_FAILURE";

export const GET_UNCLAIMEDPICKUPS_START = "GET_UNCLAIMEDPICKUPS_START";
export const GET_UNCLAIMEDPICKUPS_SUCCESS = "GET_UNCLAIMEDPICKUPS_SUCCESS";
export const GET_UNCLAIMEDPICKUPS_FAILURE = "GET_UNCLAIMEDPICKUPS_FAILURE";

export const GET_CLAIMEDPICKUPS_START = "GET_CLAIMEDPICKUPS_START";
export const GET_CLAIMEDPICKUPS_SUCCESS = "GET_CLAIMEDPICKUPS_SUCCESS";
export const GET_CLAIMEDPICKUPS_FAILURE = "GET_CLAIMEDPICKUPS_FAILURE";

export const DELETE_CLAIMEDPICKUP_START = "DELETE_CLAIMEDPICKUP_START";
export const DELETE_CLAIMEDPICKUP_SUCCESS = "DELETE_CLAIMEDPICKUP_SUCCESS";
export const DELETE_CLAIMEDPICKUP_FAILURE = "DELETE_CLAIMEDPICKUP_FAILURE";